trunk/soppa/soppa_rails/config/routes.rb
ActionController::Routing::Routes.draw do |map|

  map.connect '/bills/generate_bill/:banco', :controller => 'bills', :action => 'generate_bill'

  map.resources :friends

  map.resources :markets
  
  map.resources :cities

  map.resources :bookmark_items

  map.resources :bookmarks

  map.resources :comments

  map.resources :ingredient_types

  map.resources :ingredients

  map.resources :recipe_items

  map.resources :recipe_types

  map.resources :recipes

  map.resources :profiles
  
  map.resources :search

  
  map.logout '/logout', :controller => 'sessions', :action => 'destroy'
  map.login '/login', :controller => 'sessions', :action => 'new'
  map.register '/register', :controller => 'users', :action => 'create'
  map.signup '/signup', :controller => 'users', :action => 'new'

  map.open_id_complete 'session', :controller => "sessions", :action => "create", :requirements => { :method => :get }

  map.resources :users

  map.resources :profiles

  map.resource :session

  map.root :controller => "home"
  
  map.connect ':controller/:action/:id'
  map.connect ':controller/:action/:id.:format'
end

trunk/soppa/soppa_rails/app/models/ingredient.rb
#
# Classe que representa um ingrediente
# Autores:  Lennon Jesus - lennon.jesus@gmail.com
#           Michel de Carli - micheldecarli@gmail.com
#           Wesley Monteiro - wygres@gmail.com
#
class Ingredient < ActiveRecord::Base

  has_many :recipe_items
  has_many :recipes, :through => :recipe_items

  has_many :market_items
  has_many :markets, :through => :market_items

  has_many :market_items
  has_many :markets, :through => :market_items

  belongs_to :ingredient_type
  
  has_attached_file :photo,
                  :styles => {
                    :thumb=> "100x100#",
                    :small  => "150x150>",
                    :medium => "300x300>",
                    :large =>   "400x400>"
                  }

  validates_presence_of :name, :description, :ingredient_type
  validates_uniqueness_of :name, :case_sensitive => false

end

trunk/soppa/soppa_rails/app/models/ingredient_type.rb
#
# Classe que representa um tipo de ingrediente
# Autores:  Lennon Jesus - lennon.jesus@gmail.com
#           Michel de Carli - micheldecarli@gmail.com
#           Wesley Monteiro - wygres@gmail.com
#
class IngredientType < ActiveRecord::Base

  has_many :ingredients

  validates_presence_of :name, :description
  validates_uniqueness_of :name, :case_sensitive => false
end

trunk/soppa/soppa_rails/app/controllers/ingredients_controller.rb
#
# Classe responsavel pela logica relacionada aos ingredientes
# Autores:  Lennon Jesus - lennon.jesus@gmail.com
#           Michel de Carli - micheldecarli@gmail.com
#           Wesley Monteiro - wygres@gmail.com
#
class IngredientsController < ApplicationController

  before_filter :login_required, :except => %w[index show]

  # GET /ingredients
  # GET /ingredients.xml
  def index
    @ingredients = Ingredient.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @ingredients }
    end
  end

  # GET /ingredients/1
  # GET /ingredients/1.xml
  def show
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @ingredient }
    end
  end

  # GET /ingredients/new
  # GET /ingredients/new.xml
  def new
    @ingredient = Ingredient.new
    @ingredient_type = IngredientType.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @ingredient }
    end
  end

  # GET /ingredients/1/edit
  def edit
    @ingredient = Ingredient.find(params[:id])
    @ingredient_type = @ingredient.ingredient_type
  end

  # POST /ingredients
  # POST /ingredients.xml
  def create
    @ingredient = Ingredient.new(params[:ingredient])

    respond_to do |format|
      if @ingredient.save
        flash[:notice] = 'Ingredient was successfully created.'
        format.html { redirect_to(@ingredient) }
        format.xml  { render :xml => @ingredient, :status => :created, :location => @ingredient }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @ingredient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ingredients/1
  # PUT /ingredients/1.xml
  def update
    @ingredient = Ingredient.find(params[:id])

    respond_to do |format|
      if @ingredient.update_attributes(params[:ingredient])
        flash[:notice] = 'Ingredient was successfully updated.'
        format.html { redirect_to(@ingredient) }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @ingredient.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ingredients/1
  # DELETE /ingredients/1.xml
  def destroy
    @ingredient = Ingredient.find(params[:id])
    @ingredient.destroy

    respond_to do |format|
      format.html { redirect_to(ingredients_url) }
      format.xml  { head :ok }
    end
  end

  def search
    query = params[:id]

    @ingredients = Ingredient.name_like_all_or_description_like query

    render :partial => "results"
  end
end

trunk/soppa/soppa_rails/app/views/ingredients/_form.html.erb
<% form_for(@ingredient, :html => { :multipart => true }) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label "Tipo" %><br />
    <%= select_tag "ingredient[ingredient_type_id]", options_from_collection_for_select(IngredientType.find(:all), 'id','name', @ingredient_type.id) %>
  </p>
  <p>
    <%= f.label 'Foto' %><br />
    <%= f.file_field :photo %>
  </p>
  <p>
    <%= f.submit 'Save' %>
  </p>
<% end %>

trunk/soppa/soppa_rails/app/views/ingredients/_results.html.erb
<% for ingredient in @ingredients do  %>
  <div id="new_recipe_item_<%= ingredient.id %>" >
    <input type="checkbox" name="recipe[ingredient_ids][]" value="<%=  ingredient.id %>" class="ckb_new_ingredient_item" />
    <%= link_to ingredient.name, ingredient_path(ingredient) %>
    <input type="text" name="recipe_item_quantities[]" style="display: none;" id="txt_quantity_<%= ingredient.id.to_s %>" >
    <%= select_tag "recipe_item_units[]", options_from_collection_for_select(Unit.find(:all), 'id','name'), :id => "cmb_unit_" + ingredient.id.to_s, :style => "display: none;" %>
    <br />
  </div>
<% end %>

trunk/soppa/soppa_rails/app/views/ingredients/edit.html.erb
<h1>Editing ingredient</h1>

<%= render :partial => 'form' %>

<%= link_to 'Show', @ingredient %>

trunk/soppa/soppa_rails/app/views/ingredients/index.html.erb
<h1>Listing ingredients</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Type</th>
    <th>Foto</th>
  </tr>

<% @ingredients.each do |ingredient| %>
  <tr>
    <td><%=h ingredient.name %></td>
    <td><%=h ingredient.description %></td>
    <td><%=h ingredient.ingredient_type.name %></td>
    <td>
      <% if ingredient.photo.exists? then %>
        <%= image_tag ingredient.photo.url(:thumb) %>
      <% else %>
        <p>sem foto</p>
      <% end %>
    </td>
    <td><%= link_to 'Show', ingredient %></td>
    <td><%= link_to 'Edit', edit_ingredient_path(ingredient) %></td>
    <td><%= link_to 'Destroy', ingredient, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New ingredient', new_ingredient_path %>

trunk/soppa/soppa_rails/app/views/ingredients/new.html.erb
<h1>New ingredient</h1>

<%= render :partial => 'form' %>

trunk/soppa/soppa_rails/app/views/ingredients/show.html.erb
<p>
  <b>Name:</b>
  <%=h @ingredient.name %>
</p>

<p>
  <b>Description:</b>
  <%=h @ingredient.description %>
</p>

<p>
  <b>Type</b>
  <%=h @ingredient.ingredient_type.name %>
</p>



<%= link_to 'Edit', edit_ingredient_path(@ingredient) %>